manifest:
  remotes:
    # - name: yangxing
    #   url-base: https://github.com/yangxing844
    # - name: badjeff
    #   url-base: https://github.com/badjeff
    - name: zmkofficial
      url-base: https://github.com/zmkfirmware
    - name: gorywolf
      url-base: https://github.com/gorywolf
  projects:
    - name: zmk
      remote: zmkofficial
      revision: main
      import: app/west.yml
    # - name: zmk-pmw3610-driver
    #   remote: badjeff
    #   revision: main
    # - name: zmk-split-peripheral-input-relay
    #   remote: badjeff
    #   revision: main
    # - name: zmk-input-behavior-listener
    #   remote: badjeff
    #   revision: main
    # - name: zmk-lpm009m360a-driver
    #   remote: gorywolf
    #   revision: master
  self:
    path: config
